export const ApprovalDecisionStatus = {
  BEFORE_REQUEST_PROPOSAL: 'BEFORE_REQUEST_PROPOSAL',
  REQUEST_PROPOSAL: 'REQUEST_PROPOSAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
}; 

export const ApprovalProposalStatus = {
  BEFORE_REQUEST_PROPOSAL: 'BEFORE_REQUEST_PROPOSAL',
  WAITING_FOR_DECISIONS: 'WAITING_FOR_DECISIONS',
  IN_PROGRESS_DECISIONS: 'IN_PROGRESS_DECISIONS',
  REJECTED_BY_ANY_DECISION: 'REJECTED_BY_ANY_DECISION',
  APPROVED_BY_ALL_DECISIONS: 'APPROVED_BY_ALL_DECISIONS'
}; 